# ──────────────────────────────────────────────
# ShelfWatch — EKS Cluster Config (eksctl)
# ──────────────────────────────────────────────
# Usage: eksctl create cluster -f infra/aws/cluster.yaml
# Cost:  EKS control plane $0.10/hr + m7i-flex.large ~$0.08/hr
# ──────────────────────────────────────────────

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: shelfwatch
  region: us-east-1
  version: "1.32"

managedNodeGroups:
  - name: spot-inference-nodes-1-32
    instanceTypes: ["m7i-flex.large"]
    spot: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 30
    volumeType: gp3
    labels:
      role: inference
    tags:
      project: shelfwatch
      environment: production
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
